### ISSUE TITLE
KD Implement generic garbage detection + feedback for free-form responses in Tutor

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#198]
### Description
As part of the Ciocca funding for Adaptable Eship, we want to design a feature in Tutor that uses the research team’s natural language processing algorithms to detect generic garbage in students’ free-form responses. A student who inputs generic garbage, e.g., LOL, IDK, HAHA, will receive immediate feedback and the opportunity to try again.

Epic: https://docs.google.com/document/d/1Lkn0C6WZ1-NsJ8YYvVb7TmFUi0z4MY3J5YKCOL8SHLI/edit#heading=h.wuc3pn1ckk21

Test case document: https://docs.google.com/spreadsheets/d/155l6ID6ClmTf1oNsiFY38keffL7vRpMD4kbB_b1skrk/edit#gid=0

### Acceptance Criteria

- This feature can be turned on and off by OpenStax admin. 
- This feature can be focused (only turned on) for specific sections. 
- In a reading assignment, when a student submits a free-form response that can be categorized as generic garbage, the student gets a prompt to try again.  
- The student does not receive the prompt if s/he submits a valid or credible answer
- The student can either try again _or_ submit their original answer. 
- It takes no more than 2 seconds for the prompt to appear after a student submits a response with generic garbage. 
- When the student retries or re-submits, multiple choice options appear. 
- Multiple choice options appear in no more than 2 seconds 
- This feature is explained to students and instructors 
- We have a backup plan if the algorithm reading free-form responses is slow. It times out after TBD seconds and the multiple choice appears. 
- OpenStax admin has a flag set to get notified when the algorithm times out, or when other errors appear like more than 2 secs to display prompt or multiple choice
- The research team can see when students get the prompt: the question, the student's first response, the continue or re-submit decision, the second response, and the multiple choice

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [x] A high-level solution (development approach for the code change) is added to the issue
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

### UX Tasks

- [x] Understand the fproduct/research requirements. 
- [x] Initial concepts
- [x] Create lo-fi wireframes
- [x] Feedback
- [x] Update Lo-fi wireframes
- [x] Create test plan
- [x] Test Lo-fi wireframes
- [x] Update design based on feedback
- [x] Get Lo-fi wireframes approved
- [x] Create redlining document
- [x] Error message content approval
- [x] UX review

**Comment by dkhowala** [comment]
Link to the first draft of nudge interaction options:
https://invis.io/4DQGF3BEFQ3

**Comment by dkhowala** [comment]
Listing some additional questions I have for the research team:

1. What is the primary goal for this study– to test the efficacy of the algorithm or encourage students to write more freeform responses or any other?

2. What is the focus here to just be able to nudge based on the algorithm or nudge and see what kind of behavior it facilitates?

3. Is 'nudging to bring about a positive behavior change' a focus area of the study at all?

4. Are we actively trying to get students to rewrite answers after the nudge?

5. Are there any particular features or data sets that you want to collect or test?

6. Do we plan to have different prompts based on the kind of content detected i.e. gibberish like asdsdf VS unrelated but valid words?

7. Are we interested in setting up different experiments (through different interaction style) to compare data?

**Comment by mmmcglone** [comment]
Background: This work comes out of a grant we received from Art Ciocca to give writing feedback for students using the Entrepreneurship textbook once it's available in its assignable form - that is, once students are writing responses and we can provide feedback. Practically speaking, this means when need to implement gibberish detection in e'ship and then give some sort of feedback to the student. In order to do that work in Unified, we want to first test things in Tutor. 

So... we're implementing a generic gibberish detection algorithm in Tutor AND providing nudges to students based on whether their response is gibberish or not. 


1a. The primary goal of this work, from the research team's point of view, is to validate that our externally developed algorithm can be implemented in Tutor and work.
1b. The next goal is to determine how well the algorithm is working. Are the responses it identifies as gibberish actually gibberish? Are the responses it identifies as good actually good?  

2. I think the answer to this question is that we want to nudge based on how the algorithm assesses the response. If it's gibberish, we nudge and give the student the opportunity to rewrite the response.

**Comment by mmmcglone** [comment]
3. I wouldn't say that "nudging to bring about a positive behavior change" is a focus area of this study. We're certainly curious to see how students will respond to the nudges and hopeful that we will see fewer and fewer responses identified as gibberish as time goes on because students are putting more effort into their responses. 

4. I think this is more of a product question and less a concern for the research team. As stated above, from the research point of view our goals are to implement the algorithm successfully and validate that it's working correctly. 

5. I'm not sure the answer to this question... we want to know how the algorithm rated a response, whether the student saw the nudge, what the nudge said, and how the student responded to that nudge within the system. We already see the free form response. If they supply another response, we want to see that one too. 

6. It would be nice to have different prompts based on the different kinds of gibberish students throw our way. Is it possible to do in the MVP? I'm not sure. It would require some changes to our algorithm and given that we're talking about implementing a "generic" gibberish detection algorithm it might be outside the scope of this first semester. It's a @carlycurran question I think.

**Comment by mmmcglone** [comment]
7. Again, I don't know that this would be possible in the first semester of this work. But I also don't know how design or dev intensive it is either... maybe it could work. Again, I think we need @carlycurran to chime in. This seems more of a product related question than a research question, at least for the first implementation of this algorithm.

**Comment by carlycurran** [comment]
Here are my thoughts: 

4. Yes, once we validate that the algorithm is working, we absolutely want students to make a real attempt at the free-form response. We know that this is useful for them, whether they look up the answer and copy it directly from the book or do better than that and really give it some thought. 

5. We have a card that details the research-data we want to collect. 
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/276

In the epic, we also discuss some performance dimensions I'd like to measure: 
- Time from free-form response submission to intervention
- Time from free-form response submission to multiple choice appearance
- Number of students who try again
- Number of students who submit anyway
- Instructor feedback
- How many times the nudge times out and we don’t activate (backup plan)

6. I'm interesting in trying different responses for different types of bad answers, but since we are only focused on detecting garbage/gibberish in v1, we can't really do this yet. 

7. I think that part should happen in user testing. I'd like to try a couple of different styles and get some data/feedback around how they work BEFORE we dev anything.

**Comment by nathanstitt** [comment]
## High level overview of approach:

When a student submits a free-response we:
 * send free-response to garbage estimation service
 * record the values returned along 
 * Display a error message and allow rewrite if text is judged not valid
 * send values to tutor server along with the free-response

**Comment by dkhowala** [comment]
Nudge test Analysis: https://docs.google.com/document/d/1gsbNQUA1l_B0iP8Yv78ZUBTHcDWqS1H4tvrPPf-zrAM/edit

**Comment by dkhowala** [comment]
@nathanstitt @carlycurran 
Redlining document: https://vgxuly.axshare.com

Nathan, can you review and let me know if you need more details, please? 
Carly, can you please review and approve?

**Comment by dkhowala** [comment]
@carlycurran: I made a brief doc for writing error messages: https://docs.google.com/document/d/101bIQx8eZR8day5o8268ezbd7w2ePWJhpayrfISGz4E/edit#

If you're free sometime today, let's brainstorm over these together.

**Comment by dkhowala** [comment]
UX review link: https://invis.io/AHRCTM52PBU

**Comment by dkhowala** [comment]
@bonnebbrown : https://docs.google.com/document/d/11evNQM7sPqZJonv-S9797hTZUcjV7YFADuZOv7J8jUw/edit#
