### ISSUE TITLE
Spike implementation and data capture for research (writing the code)

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#202]
# Description
Spike implementation and data capture for research (writing the code)

# Acceptance
Garbage detection (without the UI) is running on a dev environment. It can accurately record a free-response answer, send it to the garbage detection service, and the service will return a garbage estimate (yes, this is garbage, or no, this is valid).

The result of the garbage detection will be visible when viewing the spy mode for the exercise after the free response is completed.

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~
- [x] A high-level solution (development approach for the code change) is added to the issue
-  ~If prototype code is generated, it is linked to the issue.~
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

**Comment by BruceP99166** [comment]
Q1 planning estimate: 29 points
13 - Get garbage detection running as a flask service
8 - Update Tutor FE to record free response and send to garbage detection service (no UX)
8 - Modify Tutor BE to record garbage estimate
