### ISSUE TITLE
Bring hypothesis server data into Tutor 

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#208]
# Description
As a the OpenStax Research Team, I want to give students assessments based on their highlighting activity, so that I can study whether or not highlighting is a valuable learning activity and fulfill our commitment to NSF funding.

This work, specifically, is necessary so that Tutor can record/recognize when a student highlights a certain section and then take action based on that activity.  

# Acceptance
- Highlighting data is stored in Tutor 
- The user experience is unchanged from when the highlight data was stored in Hypothesis.

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~
- [ ] A high-level solution (development approach for the code change) is added to the issue
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - ~The solution is updated.~

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.
