### ISSUE TITLE
Q3 KD#1 Prepare for project Equip pilot 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#242]
### Description
Prepare for CZI pilot by importing AP Physics and AP Bio courses into Tutor and QA-ing content and course creation + onboarding flows. 

Do not need UX. 

#### Non-dev work for the project:
- [x] Plan pilot teacher training (Carly + Phil + Micaela + Glasscock)

### Acceptance Criteria
AP Bio and AP Physics are imported into Tutor
We have a complete list of style changes we need to make
We have a complete list of any necessary content changes
We can drop the T&C for specific courses
We can check a "high school" box in the admin panel and "sections" changes to "periods"

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~A high-level solution (development approach for the code change) is added to the issue~
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.
