### ISSUE TITLE
Reading milestones displays the spaced practice as "Section" instead of the question

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#257]
### Description
Reading milestones displays the spaced practice as "Section" instead of the question

https://tutor-qa.openstax.org/course/2408/task/372445/step/2/milestones
mn45+687@rice.edu

**To Reproduce**
1. Complete a reading which has spaced practice questions
2. Click on the Milestones icon and look at the tiles for the spaced practice\
3. The spaced practice tiles are displaying "Section" instead of the question

**Expected behavior**
The spaced practice tiles should be displaying the question

**Screenshots**
![Screen Shot 2019-01-23 at 1.03.26 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/67d2373b-6f87-4225-9bff-d21bd0fc9e61)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
somewhat a dupe of #350 Fixed in #tutor-js/2668

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
