### ISSUE TITLE
Communicate intervention feature with instructors (Q2)

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#277]
### Description
As an instructor, I want to know this feature exists and why so that I’m not surprised by it when students show me or complain.

### Acceptance Criteria
- Add this to Tutor FE 
- Add this to the getting started guide
- Add this to an email campaign
- Create a video demo

### Acceptance Tests
- Updated Getting Started Guides are added to Tutor teacher and student view
- Knowledge base article is live and Nathan has link
- Demo video created 
- Email campaign sent

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
https://docs.google.com/document/d/1Lkn0C6WZ1-NsJ8YYvVb7TmFUi0z4MY3J5YKCOL8SHLI/edit

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- ~A high-level solution (development approach for the code change) is added to the issue~
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - ~Distilled acceptance tests are added to the issue.~
  - ~Automated testing criteria are added to issue.~
  - ~The solution is updated.~

### UX Tasks

- [x] Prepare content for 'Getting started guide' 
- [x] Update Indesign Document and prepare PDFs.
- [x] Prepare content for the email campaign (share it with Marcomm)
- [x] Plan how to add the content to the help section (Share it with Marcomm)
- [x] Make a demo video for the Help Article
- [x] Research preferred channel for feature update communication with instructors (FAB)
- [x] Explore when and where to surface the information on Tutor
- [x] Prepare final Specs (if required) and share on Invision

**Comment by dkhowala** [comment]
Content Document : https://drive.google.com/open?id=1jk9vQQGrUN-dtHmoHgejlJ7C3kX6TIDQYI8-7wuDKa4

**Comment by dkhowala** [comment]
UX reference: https://www.reallygoodux.io/categories/feature-release

**Comment by dkhowala** [comment]
Updated Getting Started Guides: 
https://drive.google.com/drive/folders/1TgVBY8I9Sq5tFSVkeRas3RDVePbzhDBa

@nathanstitt 

@carlycurran: Can you review once, please? I updated the student dashboard images too.

**Comment by nathanstitt** [comment]
We've just (as of this sprint) moved the "Pay Now" button so that it's to the left of the help menu.  Not sure if it's worth updating the PDF for or not

**Comment by nathanstitt** [comment]
also the highlighting says "Currently available for Biology and Introduction to Sociology 2e:" but it's now available for all subjects

**Comment by carlycurran** [comment]
Under 2-step questions, we say: When a student tries to skip the first step by entering random letters or numbers into the free-response text box, we encourage him/her to make a genuine attempt.

Can we say instead: *If* a student tries to skip the first step by entering random letters or numbers into the free-response text box, we encourage him/her to make a genuine attempt.

Other than that, for the Instructor Guide, I think Nathan's comment about highlighting being in all subjects applies here, too (p 13)

**Comment by dkhowala** [comment]
Updated getting started guides: 
https://drive.google.com/drive/folders/1c0Lvq_C5hnHKXPCLqBedVW8uX9SOBdvr
@nathanstitt @carlycurran

**Comment by nathanstitt** [comment]
@DarkPrinceFrost , @carlycurran and @dkhowala we need to remember to ask DevOps to put those in place in s3 once we're ready to go with them.

**Comment by dkhowala** [comment]
@nathanstitt @carlycurran 
The demo video for response validation: https://drive.google.com/open?id=17PRY2up2qKm5MXYYs-EECFOMIV5l4Ubu
