### ISSUE TITLE
Upgrade Tutor and Exercises

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#313]
### Description
As an OpenStaxer, I want tutor and exercises to be updated to the latest ruby/rails versions, so that we can take advantage of performance and security updates, ecosystem updates, and make future upgrades easier. 
Also, the current version of rails is end-of-life.

### Acceptance Criteria
Tutor/Exercises have no regressions

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~If UX design is needed then the UX label is added~
- [ ] A high-level solution (development approach for the code change) is added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
- [x] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [x] All child issues are closed.
>
