### ISSUE TITLE
Update Tutor content and gives users the latest version where possible KD#6

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#335]
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] A high-level solution (development approach for the code change) is added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.

**Comment by carlycurran** [comment]
We will deal with the UI part of this epic when we update the question selection interface for written-response management. Closing this epic now.
