### ISSUE TITLE
Book styling updates for AP Bio and AP Physics

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#341]
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] A high-level solution (development approach for the code change) is added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
- [x] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [x] All child issues are closed.
