### ISSUE TITLE
Reading milestones issues

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#350]
### Description
Noted few discrepancies in Reading milestones. I have highlighted them in red in the screenshot:

https://tutor-qa.openstax.org/course/2419/task/378224/step/13  student10

1. In physics, few reading steps are displayed as "Figure" in the milestone. In some cases there is a figure at the beginning of the step but in some cases it is not

2. A reading step is displaying "Reading Step #1349163". No clue what is this number from

3. The value prop cards in the milestones are having just the icons but not any text. I guess it used to say "individual review" or "*Assignment name* completed"

https://tutor-qa.openstax.org/course/2478/task/376180/step/1 . student03
https://tutor-qa.openstax.org/course/2471/task/378241/step/20 . student05

4. In biology, the interactive learning icon (video, sims, etc) in the milestones is displayed after every reading step though the question is a normal text question

5. For questions that have an image, part of the image is displayed in the milestone. Is that expected?

6. Above said, the math that used to display with all the tags in milestones are now displayed as proper math which gives the milestones a good feel :tada:

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**
![physics.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/afcc2fda-7cc4-4bd0-a3d4-5a224d65cbec)
![Screen Shot 2019-04-10 at 3.55.46 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/17209624-c030-4c79-aa2d-df8afc160392)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
@nathanstitt The following issues are still occurring: 

1. The interactive learning icon (video, sims, etc) in the milestones is displayed after every reading step though the question is a normal text question

https://tutor-qa.openstax.org/course/2471/task/378241/step/20 . student05


2. Questions that have an image, part of the image is displayed in the milestone. Or is this intended? 

https://tutor-qa.openstax.org/course/2478/task/376180/step/1 . student03

Screenshot:
![Screen Shot 2019-04-17 at 2.51.40 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/ec0a6039-958a-4e99-ae74-3a3bd74fcb93)

**Comment by nathanstitt** [comment]
the weird "interactive" icon is because the exercise is tagged that way incorrectly.

However, we shouldn't be displaying images in the previews, and we're not marking steps correct/incorrect as we should.
