### ISSUE TITLE
Q3 KD#7 Allow instructors to view Tutor as a student 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#356]
### Description
As an OpenStax Tutor user (instructor), I want to see what my students see, so that I can prepare them to use OpenStax Tutor well, show them examples, and decide how I want to set up my course.

### Acceptance Criteria

- Instructor can view the course as a student (ghost student)
- Instructor can view different sections accurately as a student
- 2nd instructor can do both of the above
- An instructor can work student assignments, see a performance forecast, and practice as a student
- An instructor can toggle back to instructor view without logging back in to his/her account
- Ghost student data does not show up in the course roster of instructor view of student scores or PF data
- All ghost student data is sent to BL and MARKED AS TEST

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else 

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [x] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

### UX Tasks

- [x] Prepare and plan for 1:1 interview with Tutor Instructors 
- [x] Conduct Interviews and summarize user needs and opportunities
- [x] Understand the current Instructor view on Tutor
- [x] Initial concepts
- [x] Create Lo-fi wireframes
- [x] Feedback
- [x] Update Lo-fi wireframes
- [x] Get wireframes approved
- [x] Create a redlining document in Invision
- [x] Create Excel for documenting feature accessibility in student view mode
- [x] Share assets
- [x] Phase 2- previewing assignments in student mode- Initial design
- [ ] UX review

**Comment by carlycurran** [comment]
Old research work: 

• https://docs.google.com/spreadsheets/d/1rT68_PaExPYIfhrxGyVPwu-c0hwlZRAIpH9ZI7haJBQ/edit#gid=1510798108

• https://docs.google.com/document/d/13fNavGQFSk9a4ZpXe_U1XNktZa6FyA8OB0B5WE_FyPU/edit

• Requests with CS- https://docs.google.com/spreadsheets/d/1NXQncRmhwG23mfxAiP1Ksbtaxo-xM98cwDAM4Wih8LI/edit#gid=0

<blockquote><img src="https://lh3.googleusercontent.com/YlsTdBtFDFnI5C-IgBjcZddTIsUdujkdkUrLk6BaGT6nhtrHEVt0UlkkZXlH9XYnyVhHFw=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/spreadsheets/d/1rT68_PaExPYIfhrxGyVPwu-c0hwlZRAIpH9ZI7haJBQ/edit?usp=embed_facebook">OpenStax Tutor feature planning</a></strong></div><div>New feature list

New feature explorations,Priority (as agreed by group),Survey evidence,Interview evidence,Competitive analysis,Other
Copy course content and settings from one course to another course, such as when reteaching,Critical,- 80.9% of 121 respondents say copying individual assignments...</div></blockquote>
<blockquote><div><strong><a href="https://docs.google.com/document/d/13fNavGQFSk9a4ZpXe_U1XNktZa6FyA8OB0B5WE_FyPU/edit">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>

**Comment by carlycurran** [comment]
‘View as a Student’ - Instructor Interview planning doc: https://docs.google.com/document/d/1B6d19LEtqJpbojkmsMuXFdnIzqMCkqq316GMh8YPOpc/edit#heading=h.8imk8jnrq70a

<blockquote><div><strong><a href="https://docs.google.com/document/d/1B6d19LEtqJpbojkmsMuXFdnIzqMCkqq316GMh8YPOpc/edit#heading=h.8imk8jnrq70a">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>

**Comment by dkhowala** [comment]
https://drive.google.com/open?id=1B3UOcaI4LkhB4cT1pEN2uY8CQaQ5vjGx

The first draft for the Student view mode, You can leave your comments on the PDF if you want.
@carlycurran @nathanstitt

Meet Google Drive – One place for all your files
Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.
