### ISSUE TITLE
Deploy free-response study using study brains to production to learn how well these work KD#2

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#360]
### Description
As the OpenStax research team,  I want Tutor to run a study that gives some students free-response boxes and gives no free-response boxes to others, so that we can review the results data and see how study brains works in practice.

### Acceptance Criteria
Free-response study runs for one month in production. 
Research can see the questions received by each student in each cohort. 

sections that :thumbsup: and :thumbsdown: for the free-form response study:
https://openstax.slack.com/archives/C74342MMJ/p1557856947005100

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [] Acceptance criteria are complete
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Testing for this has been completed. This is now ready for research to use in Production.
