### ISSUE TITLE
Verify speed of response validation server

### ISSUE THREAD

**Issue by reedstrm** [openstax/tutor#368]
### Description
As a tutor service I want response validation to run quickly, so that we can respond to students very quickly. In order to do that, we need performance data on the proposed solution.

Related to story https://github.com/openstax/tutor/issues/204
### Acceptance Criteria

Response validation server responds in < 2 sec for all likely load levels 

### Acceptance Tests

Run a bunch of load tests on diff size AWS instances w/ different scales of rates of users
Also consider effect of data-size (for this problem, it is the corpus used to consider correct answers)

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
-  ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.

**Comment by carlycurran** [comment]
1. Run base set of tests against micro server. Look at data 
2. Run tests again against small server. Look at data.
3. Determine if we need to increase instance size. 
4. Making the response validator repo package-able and deployable  
5. Take existing alg and write tests 
6. Update algorithm to deal with spell check (it takes to long when it's turned on).
