### ISSUE TITLE
Get BigLearn SPARFA online

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#46]
## Description
Fix the problems on biglearn-sparfa-server with the queue getting too full by simply not blindly adding tasks to the queue. This COULD be all we need to get Biglearn online and working with the current number of students.

## Steps 
1. Add support for redis
2. Add celery-once
That should solve the problem with the queue being too full
3. Try to make the communication with BL scheduler and BL API faster
(API changes, need to clean up PRs) Will take ~ 2 weeks. 
4. Fix up the deployment script. PR is not merge-able as-is. Solve the conflicts. (This will take the most time ~ 1 month.)
5. Fix the way we populate assignments when assignments are all open at the start of the semester. For open dates set properly, personalized will be accurate. We could revert back to populating personalized when they click it, but that would cause them to wait at blank screen when they join the course. 
***Could Add new API to BL that says if it's ready or not. Ask BL if it's ready, but don't populate assignments yet. Only populate when they actually click it.   
5. Merge
6. Deploy -- let it gather data and see if everything is working. 
Want to see: BL sched requests some calculations -- need SPARFA to respond within reasonable time, less than 5 minutes. 
7. Test (Help Malar write test plans)
78. Turn on SPARFA in Tutor

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

**Comment by carlycurran** [comment]
There is one more PR in deployment, cannot be added yet because we haven't brought that repo in to ZH.

**Comment by carlycurran** [comment]
Teachers might be opening assignments at the beginning of a course so their students can see them all on the student dashboard. They only see open assignments.

**Comment by carlycurran** [comment]
We need to set up a server (can be small one for now) for each

**Comment by carlycurran** [comment]
Dante currently going through all files in repo (BL SPARFA server) to see if they make sense. Simplifying code where he can: repeated code, spaghetti code, etc.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to QA but not yet turned on. This code will be going like though. Verified in QA that there are no performance issues with the setup.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to Staging but not yet turned on. This code will be going like though. Verified in Staging that there are no performance issues with the setup.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to Production but not yet turned on. This code will be going like though. Verified in Production that there are no performance issues with this setup.
