### ISSUE TITLE
Content Issues with Baked Books

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#51]
Testing with a baked version of College Physics for Courseware
https://tutor-content.openstax.org/book/542 (ContentTeam log in)

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.
