### ISSUE TITLE
not tracking 'clicked' correctly for external assignments

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#575]
### Description
Description

Previously, external assignments required the student to view the assignment and click the assignment URL to register as 'Clicked' on the student dashboard. Now, clicking the assignment from the dashboard is sufficient to complete the external assignment.

Old format:
clicking the external assignment from the student dashboard opened the assignment task view with the assignment name as a link (clicking it opened the external assignment URL and marked the external assignment as 'Clicked') and a back to dashboard button

Current:
clicking the external assignment from the student dashboard opens the assignment task view with the assignment name as static text, the assignment URL/link in small font below the name, and the back to dash button; opening the task view marks the assignment as 'Clicked' even if the student never clicks the assignment URL link

![Screen Shot 2019-08-26 at 2.03.13 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/76eed013-6aec-4f8e-9c93-a369e7539ad1)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
- Clicking the external assignment from the student dashboard opens the assignment task view, with the assignment name as a link.
- Clicking that link opens the external assignment URL and marks the external assignment as 'Clicked' - the student sees a back-to-dashboard button

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
