### ISSUE TITLE
Tutor - Release - 2019-09-11

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#582]
Code freeze - QA: 08/30/2019 
RC Review meeting: 09/03/2019 
Code deploy - Staging: 09/05/2019
Code Release - Production: 09/11/2019

### Emergency Preparation 
- [x] Verify automated RDS backups completed successfully. 
- [x] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  task

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v21.0.1
- [x]  openstax/accounts @ v2.3.1.1
- [x]  openstax/biglearn-api @ v13.1.0
- [x]  openstax/biglearn-local-query @ v10.1.0
- [x]  openstax/response-validator @ v2.2.1
- [x]  openstax/validator-deployment @ v2.0.0
- [x]  openstax/exercises @ v26.2.0
- [x]  openstax/tutor-js (exercises-js) @ v23.3.3
- [x]  openstax/tutor-server @ v23.3.2
- [x]  openstax/tutor-js @ v23.3.3

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment
- [x]  openstax/accounts
- [x]  openstax/exercises
- [x]  openstax/tutor-js (exercises-js)
- [x]  openstax/tutor-js

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment
- [x]  openstax/accounts
- [x]  openstax/tutor-js (exercises-js)
- [x]  openstax/tutor-js

#### After Deployment Tasks
- [ ]  dante/devops restart workers for tutor and accounts (delay_jobs)

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Tested*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v21.0.1
- [ ]  openstax/accounts @ v2.3.1.1
- [ ]  openstax/biglearn-api @ v13.1.0
- [ ]  openstax/biglearn-local-query @ v10.1.0
- [ ]  openstax/biglearn-scheduler @ X
- [ ]  openstax/biglearn-sparfa-server @ X
- [ ]  openstax/response-validator @ v2.2.1
- [ ]  openstax/validator-deployment @ v2.0.0
- [ ]  openstax/exercises @ v26.2.0
- [ ]  openstax/tutor-js (exercises-js) @ v23.3.3
- [ ]  openstax/tutor-server @ v23.3.2
- [ ]  openstax/tutor-js @ v23.3.3
-----------------------------------------------------------------------------------------

On QA Environment: *Tested*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v20.6.0
- [ ]  openstax/accounts @v2.3.1
- [ ]  openstax/biglearn-api @v13.1.0
- [ ]  openstax/biglearn-local-query @v10.1.0
- [ ]  openstax/biglearn-scheduler @ **X**
- [ ]  openstax/biglearn-sparfa-server @ **X**
- [ ]  openstax/response-validator @v2.2.1
- [ ]  openstax/validator-deployment @ v2.0.0
- [ ]  openstax/exercises @v26.2.0
- [ ]  openstax/tutor-js (exercises-js) @v23.3.3
- [ ]  openstax/tutor-server @v23.3.2
- [ ]  openstax/tutor-js @v23.3.3
-----------------------------------------------------------------------------------------

**Comment by meeragovindaraju** [comment]
Tutor-Deployment version was renamed from v20.6.1 ---> v21.0.1

**Comment by dtwilliamson** [comment]
Existing tags:

  openstax/tutor-deployment @ v20.6.0
  openstax/accounts @ v2.0.1
  openstax/biglearn-api @ v13.0.0
  openstax/biglearn-local-query @ v10.0.1
  openstax/response-validator @ v2.1.1
  openstax/validator-deployment @ e1cb36f3475f146b187c46f0422bcb4661c99f2c (master)
  openstax/exercises @ v26.1.0
  openstax/tutor-js (exercises-js) @ v23.2.4
  openstax/tutor-server @ v23.2.2
  openstax/tutor-js @ v23.2.4
