### ISSUE TITLE
Tutor - Release 09-25-2019

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#598]
Code freeze - QA: 09/13/2019 
RC Review meeting: 09/17/2019 
Code deploy - Staging: 09/19/2019
Code Release - Production: 09/25/2019

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  task

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v21.0.5
- [x]  openstax/accounts @v2.4.0
- [x]  openstax/biglearn-sparfa-server @v2.2.0
- [x]  openstax/exercises @v26.3.0
- [x]  openstax/tutor-js (exercises-js) @v24.0.7

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment
- [ ]  openstax/accounts
- [ ]  openstax/exercises
- [ ]  openstax/tutor-js (exercises-js)

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment
- [ ]  openstax/accounts
- [ ]  openstax/tutor-js (exercises-js)

#### After Deployment Tasks
- [ ]  task

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Waiting for Deploy*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v21.0.5
- [ ]  openstax/accounts @v2.4.0
- [ ]  openstax/biglearn-api @X
- [ ]  openstax/biglearn-local-query @X
- [ ]  openstax/biglearn-scheduler @X
- [ ]  openstax/biglearn-sparfa-server @v2.2.0
- [ ]  openstax/validator-deployment @X
- [ ]  openstax/response-validator @X
- [ ]  openstax/exercises @v26.3.0
- [ ]  openstax/tutor-js (exercises-js) @v24.0.7
- [ ]  openstax/tutor-server @v24.0.1
- [ ]  openstax/tutor-js @v24.0.7
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v21.0.4
- [ ]  openstax/accounts @v2.4.0
- [ ]  openstax/biglearn-api @X
- [ ]  openstax/biglearn-local-query @X
- [ ]  openstax/biglearn-scheduler @X
- [ ]  openstax/biglearn-sparfa-server @v2.2.0
- [ ]  openstax/validator-deployment @X
- [ ]  openstax/response-validator @X
- [ ]  openstax/exercises @v26.3.0
- [ ]  openstax/tutor-js (exercises-js) @v24.0.7
- [ ]  openstax/tutor-server @v24.0.1
- [ ]  openstax/tutor-js @v24.0.7
-----------------------------------------------------------------------------------------

**Comment by scb6** [comment]
existing tags: 
```
rundeck@bastion2:/var/oscms-prod/openstax-cms$ cd /var/openstax-prodtutor/tutor-deployment/
rundeck@bastion2:/var/openstax-prodtutor/tutor-deployment$ git status 
HEAD detached at v21.0.1
nothing to commit, working directory clean
rundeck@bastion2:/var/openstax-prodtutor/tutor-deployment$ cd ../accounts/
rundeck@bastion2:/var/openstax-prodtutor/accounts$ git status
HEAD detached at v2.3.1.1
nothing to commit, working directory clean
rundeck@bastion2:/var/openstax-prodtutor/accounts$ cd ../biglearn-sparfa-server/
rundeck@bastion2:/var/openstax-prodtutor/biglearn-sparfa-server$ git status 
HEAD detached at v2.1.0
nothing to commit, working directory clean
rundeck@bastion2:/var/openstax-prodtutor/biglearn-sparfa-server$ cd ../exercises
rundeck@bastion2:/var/openstax-prodtutor/exercises$ git status 
HEAD detached at v26.2.0
nothing to commit, working directory clean
rundeck@bastion2:/var/openstax-prodtutor/exercises$ cd ../exercises-js/
rundeck@bastion2:/var/openstax-prodtutor/exercises-js$ git status 
HEAD detached at v23.3.3
nothing to commit, working directory clean
rundeck@bastion2:/var/openstax-prodtutor/exercises-js$```
