### ISSUE TITLE
Tutor - Release - 2019-10-09

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#617]
Code freeze - QA: 09/27/2019 
RC Review meeting: 10/01/2019 
Code deploy - Staging: 10/03/2019
Code Release - Production: 10/09/2019

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  task

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @v21.1.2
- [ ]  openstax/accounts @v2.5.1
- [ ]  openstax/biglearn-local-query @v10.1.1
- [ ]  openstax/biglearn-scheduler @v10.1.0
- [ ]  openstax/biglearn-sparfa-server @ 2.3.1
- [ ]  openstax/response-validator @v2.3.0
- [ ]  openstax/validator-deployment @ v2.1.0
- [ ]  openstax/exercises @v26.4.1
- [ ]  openstax/tutor-js (exercises-js) @v24.1.6
- [ ]  openstax/tutor-server @v24.1.1
- [ ]  openstax/tutor-js @v24.1.6

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment
- [ ]  openstax/accounts
- [ ]  openstax/exercises
- [ ]  openstax/tutor-js (exercises-js)
- [ ]  openstax/tutor-js

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment
- [ ]  openstax/accounts
- [ ]  openstax/tutor-js (exercises-js)
- [ ]  openstax/tutor-js

#### After Deployment Tasks
- [ ]  dante/devops restart workers (delay_jobs) for tutor (and possibly for biglearn, if needed)  and that they are getting new queues
- [ ] dante/devops make sure background migrations are running
- [ ] devops for desponse validator, config change needed sudo systemctl daemon-reload and sudo systemctl restart gunicorn.\*
- [ ]  brooke turn on sparfa

#### Migrations
- [X] Yes
- [ ] No

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Passed*
###### Put an X for the repos *not* going out

- [x]  openstax/tutor-deployment @v21.1.2
- [x]  openstax/accounts @v2.5.1
- [x]  openstax/biglearn-api @X
- [x]  openstax/biglearn-local-query @v10.1.1
- [x]  openstax/biglearn-scheduler @v10.1.0
- [x]  openstax/biglearn-sparfa-server @ 2.3.1
- [x]  openstax/response-validator @v2.3.0
- [x]  openstax/validator-deployment @ v2.1.0
- [x]  openstax/exercises @v26.4.1
- [x]  openstax/tutor-js (exercises-js) @v24.1.6
- [x]  openstax/tutor-server @v24.1.1
- [x]  openstax/tutor-js @v24.1.6
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v21.1.0
- [ ]  openstax/accounts @v2.5.1
- [ ]  openstax/biglearn-api @X
- [ ]  openstax/biglearn-local-query @v10.1.1
- [ ]  openstax/biglearn-scheduler @v10.1.0
- [ ]  openstax/biglearn-sparfa-server @ 2.3.1
- [ ]  openstax/response-validator @v2.3.0
- [ ]  openstax/validator-deployment @ v2.1.0
- [ ]  openstax/exercises @v26.4.1
- [ ]  openstax/tutor-js (exercises-js) @v24.1.5
- [ ]  openstax/tutor-server @v24.1.0
- [ ]  openstax/tutor-js @v24.1.5
-----------------------------------------------------------------------------------------

**Comment by Brooke-Fail** [comment]
All items tagged for this release have been verified in production. Closing this release.
