### ISSUE TITLE
Tutor - Release 2019-10-23

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#640]
Code freeze - QA: 10/11/2019 
RC Review meeting: 10/15/2019 
Code deploy - Staging: 10/17/2019
Code Release - Production: 10/23/2019

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  task

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v22.0.0
- [x]  openstax/accounts @v2.5.2
- [x]  openstax/biglearn-scheduler @v10.2.0
- [x]  openstax/biglearn-sparfa-server @ v3.0.0
- [x]  openstax/exercises @v26.4.1
- [x]  openstax/tutor-js (exercises-js) @v25.0.6
- [x]  openstax/tutor-server @v25.0.3
- [x]  openstax/tutor-js @v25.0.6

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v22.0.0
- [x]  openstax/accounts @v2.5.2
- [x]  openstax/exercises @v26.4.1
- [x]  openstax/tutor-js (exercises-js) @v25.0.6
- [x]  openstax/tutor-js @v25.0.6

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v22.0.0
- [x]  openstax/accounts @v2.5.2
- [x]  openstax/tutor-js @v25.0.6

### Migrations
- [X] Yes 
- [ ] No 

#### After Deployment Tasks
- [ ]  dante/devops restart workers for tutor and accounts (delay_jobs)

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Passed*
###### Put an X for the repos *not* going out

- [x]  openstax/tutor-deployment @v22.0.0
- [x]  openstax/accounts @v2.5.2
- [x]  openstax/biglearn-api X
- [x]  openstax/biglearn-local-query X
- [x]  openstax/biglearn-scheduler @v10.2.0
- [x]  openstax/biglearn-sparfa-server @ v3.0.0
- [x]  openstax/response-validator X
- [x]  openstax/validator-deployment X
- [x]  openstax/exercises @v26.4.1
- [x]  openstax/tutor-js (exercises-js) @v25.0.6
- [x]  openstax/tutor-server @v25.0.3
- [x]  openstax/tutor-js @v25.0.6
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v22.0.0
- [ ]  openstax/accounts @v2.5.2
- [ ]  openstax/biglearn-api @ X
- [ ]  openstax/biglearn-local-query @ X
- [ ]  openstax/biglearn-scheduler @v10.2.0
- [ ]  openstax/biglearn-sparfa-server @ v3.0.0
- [ ]  openstax/response-validator @ X
- [ ]  openstax/validator-deployment @ X
- [ ]  openstax/exercises @v26.4.1
- [ ]  openstax/tutor-js (exercises-js) @v25.0.5
- [ ]  openstax/tutor-server @v25.0.3
- [ ]  openstax/tutor-js @v25.0.5
-----------------------------------------------------------------------------------------

**Comment by dtwilliamson** [comment]
Existing tags for production pre-deploy:

 openstax/tutor-deployment @v21.1.2
 openstax/accounts @v2.5.1
 openstax/biglearn-scheduler @v10.1.0
 openstax/biglearn-sparfa-server @ v2.3.1
 openstax/exercises @v26.4.1
 openstax/tutor-js (exercises-js) @v24.1.6
 openstax/tutor-server @v24.1.1
 openstax/tutor-js @v24.1.6
