### ISSUE TITLE
Deploy -- gather data and see if everything is working

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#71]
Want to see: BL scheduler request some calculations -- need SPARFA to respond within reasonable time, less than 5 minutes.

**Tasks**
Flip Tutor-dev to use SPARFA
Dante to verify in dev: 
- PF rendering
- Dashboard loads
- Make sure assignment gets PE
- Scores 

Deploy to QA ahead of 12/4 release
Can flip Tutor-QA to use SPARFA right after release week of 12/4

**Regression testing**
Dante to give Malar existing student names who have exercises (lot & lengthy)
Do we need research to come in?	
YES, after basic testing
Make sure that student assignments don’t load PE at creation
Can check for this in teacher assignment view (?) 
May have to look at database 
Test with big class and lengthy assignments

**What we need to test**
Regression testing 
Add scores testing
Tutor should work as it does now
We do not see a change in: 
Assignment load time
Dashboard load time
Scores load time
Performance forecast load time
Existing assignments - exercises you have already seen or responded to
Spaced practice exercises 

Try comparative testing with Biglearn local query vs SPARFA
Test on a bunch of students & assignments with local query (save the results)
Dante to revert the testing and switch to SPARFA
Retest with same students & assignments on SPARFA
Compare the test results

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to QA but not yet turned on. This code will be going like though. Verified in QA that there are no performance issues with the setup.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to Staging but not yet turned on. This code will be going like though. Verified in Staging that there are no performance issues with the setup.

**Comment by Brooke-Fail** [comment]
SPARFA has been deployed to Production but not yet turned on. This code will be going like though. Verified in Production that there are no performance issues with this setup.
